dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  webview_flutter: ^4.0.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  firebase_messaging: ^14.0.0
  in_app_purchase: ^4.0.0
  provider: ^6.0.0
